### ISSUE TITLE
Project creation issue after Apigee Edge RC5

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-devportal-kickstart-drupal#117]
![image](https://user-images.githubusercontent.com/1755573/58415539-10a59600-807f-11e9-8271-df4721333f6c.png)

https://github.com/apigee/apigee-edge-drupal/pull/197#issuecomment-496053544

**Comment by mxr576** [comment]
Hi @epowelljr.

I opened this new issue from your comment in the project that this could be related.

**Comment by cnovak** [comment]
@epowelljr we are putting in a new release to fix this issue, will keep this ticket updated.

**Comment by epowelljr** [comment]
Thank you very much Chris!

-Edgar

**Comment by cnovak** [comment]
You are welcome @epowelljr. We just released [Kickstart 1.0-rc1](https://www.drupal.org/project/apigee_devportal_kickstart/releases/8.x-1.0-rc1) which I validated fixes this issue.  Update your project using `composer update -o --with-dependencies` to get the latest.  You might also want to update your project composer file to [remove Swagger UI library](https://github.com/apigee/devportal-kickstart-project-composer/compare/919422c...eec3c73) if you are no longer planning on using it.  By default we now user Apigee SmartDocs to render OpenAPI specs in the [Apigee API Catalog module](https://www.drupal.org/project/apigee_api_catalog) instead of Swagger UI.

**Comment by epowelljr** [comment]
This is wonderful Chris!

Please keep me informed when there are now updates.

Have a great day!

**Comment by cnovak** [comment]
Great to hear, thanks @epowelljr

**Comment by epowelljr** [comment]
I’m still having issues with the Apigee kickstart Drupal portal installation.

I installed the portal on Prem. It was a LAMP installation using MariaDB as the Database. The Sever is Redhat.

1. The portal work fine when a user is just surfacing through the portal page and content. 
2. If you login to the portal you will notice the interface had normal structure. The portal display lists of folder. 
3. When you logout of the portal you will get a 404 error.


A. So, I renamed the .htaccess files located in Drupal root and I noticed I could not login or access any pages. I would get the 404 error. So, I change the name back to .htaccess. Now, I can access all the pages. I can login to the Portal as well but when I login the I noticed the content and Drupal interface structure breaks. There are lists of folder displaying throughout the portal.

Can you help?
Thanks
Edgar

**Comment by jacine** [comment]
Hi @epowelljr,

Did you try the suggestions we posted for you in #136?

Are you sure that you have `mod_rewrite` enabled?  Here is another documentation page that might be useful for you: https://www.drupal.org/node/228462.

Thanks,
Jacine

**Comment by cnovak** [comment]
@epowelljr here is a doc on how to get [Drupal 8 running on RHEL](https://www.web3us.com/drupal-how-guides/install-drupal-8-composer-and-drush-9) without our Kickstart.  You can replace step number 7 in this doc with the Kickstart composer project command.

**Comment by epowelljr** [comment]
Where is the link to the doc?

**Comment by kscheirer** [comment]
I've followed up with Edgar over email to help resolve his issues, this does not appear to be a problem in Kickstart.
